env:
  browser: true
  commonjs: true
  es2020: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
